deployment:
  name: $APP_NAME
  image:
    name: $APP_NAME
    repository: 429919990249.dkr.ecr.eu-west-1.amazonaws.com/mygreatcluster.k8s.local
    version: $APP_VERSION
  containerPort: 4003
  replicas: 2
  env:
    - name: NODE_ENV
      value: production
